# Лабораторная работа 5


1.   Использовать предобработанные тексты выбранного корпуса
2.   Извлечь вектора BoW, TF-IDF, Word2Vec
3.   Сохранить полученные вектора отдельным файлом (.npy
/ .csv)
4.   ** Предсказать сентимент отзывов используя тональные
словари

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/preprocessed_data_soobshchestva_itmo.csv")
df.head()

id_group  id_post                 data  \
0       -94    57196  2024-04-12 13:00:03   
1       -94    57194  2024-04-12 09:00:02   
2       -94    57190  2024-04-11 09:00:01   
3       -94    57182  2024-04-10 12:39:06   
4       -94    57181  2024-04-10 11:41:01   

                                         description         title  \
0                                                NaN           NaN   
1                                                NaN           NaN   
2                                                NaN           NaN   
3  Где узнать больше о DevOps и IT в целом? 13 ап...  Клип @itmoru   
4                                                NaN           NaN   

                                                text   views  likes  reposts  \
0               Пятница! А где тусуются айтишники? 👇  7473.0     11        6   
1  Каждый из нас, своего рода, художник 👨🏻‍🎨 \n \...  1542.0      3        2   
2  Мы его ждали и он возвращается! Грандиозный, л...  3634.0     89       55   
3  Тут про свежую IT-конференцию👇🏻\n\nВ ролике Вя...  3703.0     18       11   
4  Прекрасные весенние новости! ИТМО — лучший рос...  4597.0    106       18   

                                      processed_text  
0                        пятница тусоваться айтишник  
1  каждый свой род художник особенно наш друг сев...  
2  ждать возвращаться грандиозный летний свежий i...  
3  свежий it-конференция ролик вячеслав евстрат s...  
4  прекрасный весенний новость итмый хороший росс...

In [ ]:
#сохраняем столбец processed_text в массив строк
db = []
for index, row in df.iterrows():
    db.append(row['processed_text'])
#удаляем все типы кроме str
corpus = [text for text in db if isinstance(text, str) and text != 'nan']
corpus

['пятница тусоваться айтишник',
 'каждый свой род художник особенно наш друг севкабель порт проходить art fair ежегодный ярмарка направить поддержка современный искусство объединение арт-сцена независимый художник секция галерея сегмент дизайн digital-искусство всё это ждать посетитель апрель двое смочь выиграть билет конкурс придумать свой нейро-искусство загрузить описание картина который хотеть получить любой нейросеть придумать название неповторимый арт отправлять коммент это пост апрель выбрать два самый креативный участник получить билет ярмарка',
 'ждать возвращаться грандиозный летний свежий itmo family day пройти июль год вместе выпускной это × улыбка крутой воспоминание ждать елагин остров интерактивный зона специальный гость мощный партнёр главное самый любимый itmo family звать студент учёный партнёр выпускник преподаватель просто фанат итмый обводить дата календарь скоро рассказать подробный программа',
 'свежий it-конференция ролик вячеслав евстрат senior-инженер тимлида 

In [ ]:
#BoW
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
#векторизуем сразу весь корпус
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
#в предобученный векторизатор подаем новый текст
vectorizer.transform(['казаться','выходной','трудовой','будни','врываться','пара','день','связь','вопрос','мем']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
#сохраняем полученный вектор путем BoW
bow_df = pd.DataFrame(X)
bow_df.to_csv('/content/drive/MyDrive/bow_vectors.csv', index=False)

In [ ]:
#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorizer = TfidfVectorizer()
X_2 = vectorizer.fit_transform(corpus).toarray()
X_2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
#сохраняем полученный вектор путем TF-IDF
TFIDF_df = pd.DataFrame(X_2)
TFIDF_df.to_csv('/content/drive/MyDrive/TF-IDF_vectors.csv', index=False)

In [ ]:
#Word2Vec
import gensim.downloader as api

In [ ]:
#загрузка предобученную модель
wv = api.load('word2vec-ruscorpora-300')

In [ ]:
#создание списка слов без частей речи
vocab = []
for w in list(wv.index_to_key):
  vocab.append(w.split('_')[0])

In [ ]:
vectors_text = []
for text in corpus:
  vectors_word = []
  words = text.split()
  for i in words:
    if i in vocab:
      vectors_word.append(wv[list(wv.index_to_key)[vocab.index(i)]])
    else:
      vectors_word.append(np.zeros(300))
  vectors_text.append(np.mean(vectors_word, axis = 0))

In [ ]:
#количество векторов
len(vectors_text)

14054

In [ ]:
#Пример вывода первых двух векторов размером 300 чисел
for i in range(2):
    print(f"Вектор {i+1}:")
    print(vectors_text[i])
    print()

Вектор 1:
[-0.06475276  0.00477081  0.01552755  0.0054091   0.00499552  0.02010559
  0.04341618 -0.02475645 -0.02663288  0.04493363 -0.04104608 -0.02014024
 -0.02920179 -0.03657216  0.0962095   0.01851475 -0.00470427  0.02132577
  0.00978082 -0.00869425  0.02618527 -0.04444114 -0.04092969  0.07871527
 -0.00152612 -0.06229369  0.02316494 -0.0706343   0.00869195 -0.03267373
  0.02383367 -0.00881499 -0.01542552  0.00675098  0.01203914 -0.00377649
 -0.02944122 -0.03310272 -0.01089175  0.01866914  0.01226094 -0.01555127
 -0.01951108  0.03841342 -0.03044814 -0.01433219  0.06260946  0.04193528
  0.05017349 -0.01512629 -0.06038069  0.05464755 -0.00709802  0.07141326
  0.00509787 -0.06187137 -0.02345315 -0.02257358  0.018335    0.04925404
 -0.04200475 -0.03806325 -0.02619333  0.02459833 -0.0009865  -0.04225548
 -0.01238475  0.0523404  -0.00985439 -0.0215076  -0.02627234  0.01506416
  0.04535431 -0.08214609 -0.00973677  0.05682127  0.00503321 -0.0492378
  0.06049884 -0.06708732 -0.03468313  0.02

In [ ]:
# Сохранение векторов в файл .npy
np.save('/content/drive/MyDrive/word2vec_vectors.npy', vectors_text)